const NOTIFICATION_TYPES = {
  RESULT_PUBLISHED: "RESULT_PUBLISHED",
  RESULT_FAIL: "RESULT_FAIL",

  REAPPEAR_APPROVED: "REAPPEAR_APPROVED",
  REAPPEAR_REJECTED: "REAPPEAR_REJECTED",

  ACHIEVEMENT_APPROVED: "ACHIEVEMENT_APPROVED",
  ACHIEVEMENT_REJECTED: "ACHIEVEMENT_REJECTED",

  SUBJECT_ASSIGNED: "SUBJECT_ASSIGNED",

  TIMETABLE_APPROVED: "TIMETABLE_APPROVED",
};

module.exports = NOTIFICATION_TYPES;